sonar.sourceEncoding=UTF-8
sonar.sources=src,scripts
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts
sonar.exclusions=coverage/**,dist/**,node_modules/**
sonar.coverage.exclusions=scripts/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
